/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import DAO.PrestataireDao;
import Controlleur.ListePrestataireControlleur;
import Entites.Prestataire;

/**
 *
 * @author triki
 */
public class ListeDesPrestataires extends javax.swing.JFrame {

    static int choix;

    /**
     * Creates new form ListeDesPrestataires
     */
    public ListeDesPrestataires() {
        initComponents();
        // jTable2.setVisible(false);
        this.disableAll();
        jTextCode.setText(Integer.toString(0));
    }

    public void disableAll() {
        TextNom.setEnabled(false);
        TextPrenom.setEnabled(false);
        TextAdress.setEnabled(false);
        TextMdp.setEnabled(false);
        TextMail.setEnabled(false);
        TextTel.setEnabled(false);
        jTextCode.setEnabled(false);


    }

    public void enableAll() {
        TextNom.setEnabled(true);
        TextPrenom.setEnabled(true);
        TextAdress.setEnabled(true);
        TextMdp.setEnabled(true);
        TextMail.setEnabled(true);
        TextTel.setEnabled(true);
        jTextCode.setEnabled(true);

    }

    public void initText() {
        TextNom.setText("");
        TextPrenom.setText("");
        TextAdress.setText("");
        TextMdp.setText("");
        TextMail.setText("");
        TextTel.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextNom = new javax.swing.JTextField();
        TextPrenom = new javax.swing.JTextField();
        TextAdress = new javax.swing.JTextField();
        TextMdp = new javax.swing.JTextField();
        TextTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextMail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        supprimer = new javax.swing.JLabel();
        ajouter = new javax.swing.JLabel();
        valider = new javax.swing.JLabel();
        retour = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextCode = new javax.swing.JTextField();
        modifier = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom");

        jLabel2.setText("Prenom");

        jLabel3.setText("Adress");

        jLabel4.setText("Tel");

        jLabel5.setText("Mot De Passe");

        jLabel6.setText("Mail");

        TextMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMailActionPerformed(evt);
            }
        });

        jTable2.setModel(new ListePrestataireControlleur());
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Prestataire de services");

        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerMouseClicked(evt);
            }
        });

        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
        });

        valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Valid.png"))); // NOI18N
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerMouseClicked(evt);
            }
        });

        retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/retour.png"))); // NOI18N
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourMouseClicked(evt);
            }
        });

        jLabel8.setText("Code");

        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifierMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TextTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(TextMdp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextAdress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextNom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextMail)
                            .addComponent(jTextCode, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(modifier)
                        .addGap(55, 55, 55)
                        .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(retour, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(TextMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(TextMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(valider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(retour, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMailActionPerformed

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked
        jTextCode.setText(Integer.toString(0));

        ajouter.setEnabled(false);


        supprimer.setEnabled(false);

        valider.setEnabled(true);
        retour.setEnabled(true);
        this.enableAll();
        choix = 1;

        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterMouseClicked

    private void supprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerMouseClicked

        ajouter.setEnabled(false);

        supprimer.setEnabled(false);

        valider.setEnabled(true);
        retour.setEnabled(true);

        choix = 2;

        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerMouseClicked

    private void validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseClicked

        Prestataire pr = new Prestataire();
        PrestataireDao prdao = new PrestataireDao();
        switch (choix) {
            case 1:
                pr.setAdress(TextAdress.getText());
                pr.setMail(TextMail.getText());
                pr.setMot_De_Passe(TextMdp.getText());
                pr.setNom(TextNom.getText());
                pr.setTel(Integer.parseInt(TextTel.getText()));
                pr.setPrenom(TextPrenom.getText());
                pr.setCode(Integer.parseInt(jTextCode.getText()));
                prdao.ajouterPrestataire(pr);


                jTable2 = new javax.swing.JTable();

                jTable2.setModel(new ListePrestataireControlleur());

                jScrollPane2.setViewportView(jTable2);

                break;
            case 2:

                int id = (Integer) jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 0);

                prdao.DeletePrestataire(id);



                jTable2 = new javax.swing.JTable();

                jTable2.setModel(new ListePrestataireControlleur());

                jScrollPane2.setViewportView(jTable2);
                break;

            case 3:
                int id1 = (Integer) jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 0);
                pr.setId_Prestataire(id1);
                pr.setCode(Integer.parseInt(jTextCode.getText()));
                prdao.Modifier(pr);
                jTable2 = new javax.swing.JTable();
                jTable2.setModel(new ListePrestataireControlleur());
                jScrollPane2.setViewportView(jTable2);
                break;
        }
        ajouter.setEnabled(true);

        supprimer.setEnabled(true);

        valider.setEnabled(false);
        retour.setEnabled(false);
        this.initText();
        this.disableAll();









        // TODO add your handling code here:
    }//GEN-LAST:event_validerMouseClicked

    private void retourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseClicked
        jTextCode.setText(Integer.toString(0));


        ajouter.setEnabled(true);

        supprimer.setEnabled(true);

        valider.setEnabled(false);
        retour.setEnabled(false);
        this.initText();
        this.disableAll();

        // TODO add your handling code here:
    }//GEN-LAST:event_retourMouseClicked

    private void modifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifierMouseClicked
       
                System.out.println("hello");
        
        int id = (Integer) jTable2.getModel().getValueAt(jTable2.getSelectedRow(),7);
        jTextCode.setText(Integer.toString(id));

        ajouter.setEnabled(false);
        modifier.setEnabled(false);
        supprimer.setEnabled(false);

        valider.setEnabled(true);
        retour.setEnabled(true);
        this.jTextCode.setEnabled(true);
        choix = 3;        // TODO add your handling code here:
    }//GEN-LAST:event_modifierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeDesPrestataires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeDesPrestataires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeDesPrestataires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeDesPrestataires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeDesPrestataires().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextAdress;
    private javax.swing.JTextField TextMail;
    private javax.swing.JTextField TextMdp;
    private javax.swing.JTextField TextNom;
    private javax.swing.JTextField TextPrenom;
    private javax.swing.JTextField TextTel;
    private javax.swing.JLabel ajouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextCode;
    private javax.swing.JLabel modifier;
    private javax.swing.JLabel retour;
    private javax.swing.JLabel supprimer;
    private javax.swing.JLabel valider;
    // End of variables declaration//GEN-END:variables
}
